### ISSUE TITLE
enable discussions tab

### ISSUE THREAD

**Issue by yonicd** [openpharma/clindata#1]
### Feature description

@danielinteractive can you enable the discussions tab to allow for a separate area from issues for conversations about ideas

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

**Comment by danielinteractive** [comment]
done and also gave you admin access now (so you can do those things yourself next time)

**Comment by yonicd** [comment]
ty!
